version: '3.7'

services:

  app:
    image: my-app
    ports:
      - "9000:8081"
    environment:
      spring.datasource.url: "jdbc:mysql://database:3306/mydatabase?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
    networks:
      - users-network

  database:
    image: mysql:8.0
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - "9001:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    networks:
      - users-network

networks:
    users-network:
        driver: bridge